'use client';

import React, { useEffect, useRef, useState } from 'react';
import { getVerificationPathFromScan } from '@/lib/qrEquipment';

interface BarcodeDetectorLike {
  detect: (source: HTMLVideoElement) => Promise<Array<{ rawValue: string }>>;
}

interface QrScannerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onScanned: (verificationPath: string) => void;
}

export function QrScannerModal({ isOpen, onClose, onScanned }: QrScannerModalProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const timerRef = useRef<number | null>(null);
  const [status, setStatus] = useState<'idle' | 'starting' | 'scanning' | 'unsupported' | 'error'>('idle');
  const [message, setMessage] = useState('');
  const [manualValue, setManualValue] = useState('');

  const stopCamera = () => {
    if (timerRef.current) window.clearInterval(timerRef.current);
    timerRef.current = null;
    streamRef.current?.getTracks().forEach((track) => track.stop());
    streamRef.current = null;
  };

  useEffect(() => {
    if (!isOpen) {
      stopCamera();
      return;
    }

    let active = true;
    const BarcodeDetectorConstructor = (window as Window & {
      BarcodeDetector?: new (options?: { formats?: string[] }) => BarcodeDetectorLike;
    }).BarcodeDetector;

    if (!BarcodeDetectorConstructor || !navigator.mediaDevices?.getUserMedia) {
      queueMicrotask(() => {
        setStatus('unsupported');
        setMessage('Camera scanning is not available in this browser. Open the printed QR with your phone camera, or paste its link below.');
      });
      return () => stopCamera();
    }

    const startScanner = async () => {
      setStatus('starting');
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { facingMode: { ideal: 'environment' } },
          audio: false,
        });
        if (!active) {
          stream.getTracks().forEach((track) => track.stop());
          return;
        }

        streamRef.current = stream;
        const video = videoRef.current;
        if (!video) return;
        video.srcObject = stream;
        await video.play();

        const detector = new BarcodeDetectorConstructor({ formats: ['qr_code'] });
        setStatus('scanning');
        setMessage('Point your camera at an equipment QR code.');

        timerRef.current = window.setInterval(async () => {
          if (!active || video.readyState < HTMLMediaElement.HAVE_ENOUGH_DATA) return;
          try {
            const results = await detector.detect(video);
            const rawValue = results[0]?.rawValue;
            if (!rawValue) return;
            const path = getVerificationPathFromScan(rawValue, window.location.origin);
            if (path) {
              stopCamera();
              onScanned(path);
            } else {
              setMessage('That QR code is not an equipment verification label for this inventory.');
            }
          } catch {
            // A frame can fail to decode; keep looking at the next frame.
          }
        }, 350);
      } catch (error) {
        if (!active) return;
        setStatus('error');
        const reason = error instanceof Error ? error.message : 'Camera permission was not granted.';
        setMessage(`Could not start the camera: ${reason}`);
      }
    };

    void startScanner();
    return () => {
      active = false;
      stopCamera();
    };
  }, [isOpen, onScanned]);

  const handleManualOpen = () => {
    const path = getVerificationPathFromScan(manualValue.trim(), window.location.origin);
    if (!path) {
      setMessage('Paste the full QR link generated by this inventory app.');
      return;
    }
    onScanned(path);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-end justify-center bg-zinc-950/70 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="qr-scanner-title">
      <div className="w-full max-w-md rounded-t-3xl bg-white shadow-2xl dark:bg-zinc-900 sm:rounded-3xl">
        <div className="flex items-start justify-between border-b border-zinc-100 px-5 py-4 dark:border-zinc-800">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-600 dark:text-blue-400">On-site verification</p>
            <h2 id="qr-scanner-title" className="mt-0.5 text-base font-bold text-zinc-900 dark:text-zinc-50">Scan equipment QR</h2>
          </div>
          <button onClick={onClose} className="rounded-xl p-2 text-zinc-400 transition hover:bg-zinc-100 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-200" aria-label="Close QR scanner">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18 18 6M6 6l12 12" /></svg>
          </button>
        </div>

        <div className="space-y-4 p-5">
          <div className="relative overflow-hidden rounded-2xl bg-zinc-900 aspect-square">
            <video ref={videoRef} className="h-full w-full object-cover" muted playsInline />
            <div className="pointer-events-none absolute inset-[15%] rounded-2xl border-2 border-white/90 shadow-[0_0_0_999px_rgba(0,0,0,0.18)]" />
            {status === 'starting' && <div className="absolute inset-0 grid place-items-center text-sm font-medium text-white">Starting camera…</div>}
            {(status === 'unsupported' || status === 'error') && (
              <div className="absolute inset-0 grid place-items-center p-6 text-center text-sm text-zinc-300">Use your phone’s camera to open the label, or paste its link below.</div>
            )}
          </div>

          <p className={`text-center text-xs ${status === 'error' ? 'text-rose-600 dark:text-rose-400' : 'text-zinc-500 dark:text-zinc-400'}`} aria-live="polite">{message}</p>

          <div className="border-t border-zinc-100 pt-4 dark:border-zinc-800">
            <label className="text-[11px] font-semibold text-zinc-600 dark:text-zinc-300">Camera unavailable? Paste the QR link</label>
            <div className="mt-1.5 flex gap-2">
              <input value={manualValue} onChange={(event) => setManualValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') handleManualOpen(); }} placeholder="https://…/verify?asset=…" className="min-w-0 flex-1 rounded-xl border border-zinc-200 bg-white px-3 py-2 text-xs text-zinc-900 outline-none placeholder:text-zinc-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/15 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-100" />
              <button onClick={handleManualOpen} className="rounded-xl bg-zinc-900 px-3 text-xs font-semibold text-white transition hover:bg-zinc-700 dark:bg-white dark:text-zinc-900">Open</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
