'use client';

import React, { useEffect, useRef, useState, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { getVerificationPathFromScan } from '@/lib/qrEquipment';

interface BarcodeDetectorLike {
  detect: (source: HTMLVideoElement) => Promise<Array<{ rawValue: string }>>;
}

type ScanStatus = 'starting' | 'scanning' | 'unsupported' | 'error' | 'scanned';

export function ScannerPage() {
  const router = useRouter();
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const timerRef = useRef<number | null>(null);
  const isDetectingRef = useRef(false);
  const hasScannedRef = useRef(false);

  const [status, setStatus] = useState<ScanStatus>('starting');
  const [message, setMessage] = useState('');
  const [manualValue, setManualValue] = useState('');
  const [flashActive, setFlashActive] = useState(false);

  const stopCamera = useCallback(() => {
    if (timerRef.current) window.clearInterval(timerRef.current);
    timerRef.current = null;
    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;
  }, []);

  const handleScanned = useCallback((path: string) => {
    hasScannedRef.current = true;
    stopCamera();
    setStatus('scanned');
    setFlashActive(true);
    router.push(path);
  }, [router, stopCamera]);

  useEffect(() => {
    let active = true;
    hasScannedRef.current = false;
    isDetectingRef.current = false;

    const BarcodeDetectorConstructor = (window as Window & {
      BarcodeDetector?: new (options?: { formats?: string[] }) => BarcodeDetectorLike;
    }).BarcodeDetector;

    const startScanner = async () => {
      if (!BarcodeDetectorConstructor || !navigator.mediaDevices?.getUserMedia) {
        setStatus('unsupported');
        setMessage('Camera scanning is not available in this browser. Paste the QR link below.');
        return;
      }

      setStatus('starting');
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { facingMode: { ideal: 'environment' } },
          audio: false,
        });
        if (!active) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }
        streamRef.current = stream;
        const video = videoRef.current;
        if (!video) return;
        video.srcObject = stream;
        await video.play();

        const detector = new BarcodeDetectorConstructor({ formats: ['qr_code'] });
        setStatus('scanning');
        setMessage('Point your camera at an equipment QR code.');

        timerRef.current = window.setInterval(async () => {
          if (!active || hasScannedRef.current || isDetectingRef.current || video.readyState < HTMLMediaElement.HAVE_ENOUGH_DATA) return;
          isDetectingRef.current = true;
          try {
            const results = await detector.detect(video);
            const rawValue = results[0]?.rawValue;
            if (!rawValue) return;
            const path = getVerificationPathFromScan(rawValue, window.location.origin);
            if (path) {
              handleScanned(path);
            } else {
              setMessage('That QR code is not an equipment label for this inventory.');
            }
          } catch {
            // A frame can fail to decode; keep looking.
          } finally {
            isDetectingRef.current = false;
          }
        }, 140);
      } catch (err) {
        if (!active) return;
        setStatus('error');
        const reason = err instanceof Error ? err.message : 'Camera permission was not granted.';
        setMessage(`Could not start the camera: ${reason}`);
      }
    };

    void startScanner();
    return () => {
      active = false;
      stopCamera();
    };
  }, [handleScanned, stopCamera]);

  const handleManualOpen = () => {
    const path = getVerificationPathFromScan(manualValue.trim(), window.location.origin);
    if (!path) {
      setMessage('Paste the full QR link generated by this inventory app.');
      return;
    }
    handleScanned(path);
  };

  return (
    <main className="relative flex min-h-screen flex-col items-center bg-zinc-950">
      {/* Flash overlay on successful scan */}
      {flashActive && (
        <div className="pointer-events-none fixed inset-0 z-50 animate-ping bg-emerald-400/30" />
      )}

      {/* Header */}
      <div className="relative z-10 w-full px-4 pt-safe-top">
        <div className="mx-auto flex w-full max-w-lg items-center justify-between py-4">
          <div className="flex items-center gap-3">
            <div className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-green-600 to-blue-600 text-white shadow-lg shadow-blue-500/20">
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4h5v2H6v3H4V4Zm11 0h5v5h-2V6h-3V4ZM4 15h2v3h3v2H4v-5Zm14 0h2v5h-5v-2h3v-3ZM9 9h6v6H9V9Z" />
              </svg>
            </div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-400">PENRO Batanes · ICT</p>
              <h1 className="text-base font-bold text-white">QR Scanner</h1>
            </div>
          </div>
          <Link
            href="/"
            className="flex items-center gap-1.5 rounded-xl border border-zinc-700 bg-zinc-800 px-3 py-2 text-xs font-semibold text-zinc-300 transition hover:bg-zinc-700 hover:text-white"
          >
            <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9.75L12 3l9 6.75V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.75z" /></svg>
            Dashboard
          </Link>
        </div>
      </div>

      {/* Camera viewfinder — fills the screen */}
      <div className="relative w-full flex-1">
        <video
          ref={videoRef}
          className="h-full w-full object-cover"
          style={{ minHeight: 'calc(100svh - 180px)' }}
          muted
          playsInline
        />

        {/* Dark overlay with transparent cutout */}
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div className="relative h-64 w-64 sm:h-72 sm:w-72">
            {/* Four corner brackets */}
            <span className="absolute left-0 top-0 h-10 w-10 rounded-tl-2xl border-l-4 border-t-4 border-white" />
            <span className="absolute right-0 top-0 h-10 w-10 rounded-tr-2xl border-r-4 border-t-4 border-white" />
            <span className="absolute bottom-0 left-0 h-10 w-10 rounded-bl-2xl border-b-4 border-l-4 border-white" />
            <span className="absolute bottom-0 right-0 h-10 w-10 rounded-br-2xl border-b-4 border-r-4 border-white" />

            {/* Animated scan line */}
            {status === 'scanning' && (
              <span className="absolute inset-x-2 top-0 h-0.5 animate-[scanline_2s_ease-in-out_infinite] rounded-full bg-emerald-400 shadow-[0_0_8px_2px_rgba(52,211,153,0.7)]" />
            )}
          </div>
        </div>

        {/* Status overlay */}
        {status === 'starting' && (
          <div className="absolute inset-0 flex items-center justify-center bg-zinc-950/70">
            <div className="flex flex-col items-center gap-3">
              <svg className="h-8 w-8 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
              </svg>
              <p className="text-sm font-medium text-white">Starting camera…</p>
            </div>
          </div>
        )}

        {(status === 'unsupported' || status === 'error') && (
          <div className="absolute inset-0 flex items-center justify-center bg-zinc-950/80 p-8">
            <div className="text-center">
              <div className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl bg-rose-500/20 text-rose-400">
                <svg className="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.069A1 1 0 0121 8.867V15.133a1 1 0 01-1.447.902L15 14M3 8h12a2 2 0 012 2v4a2 2 0 01-2 2H3a2 2 0 01-2-2v-4a2 2 0 012-2z" /></svg>
              </div>
              <p className="text-sm font-semibold text-white">Camera unavailable</p>
              <p className="mt-1 text-xs text-zinc-400">{message}</p>
            </div>
          </div>
        )}

        {status === 'scanned' && (
          <div className="absolute inset-0 flex items-center justify-center bg-emerald-950/80">
            <div className="flex flex-col items-center gap-3">
              <div className="grid h-16 w-16 place-items-center rounded-full bg-emerald-500 text-white shadow-lg shadow-emerald-500/40">
                <svg className="h-9 w-9" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="m5 13 4 4L19 7" /></svg>
              </div>
              <p className="text-sm font-bold text-white">QR Scanned! Loading…</p>
            </div>
          </div>
        )}
      </div>

      {/* Bottom panel */}
      <div className="relative z-10 w-full bg-zinc-900 px-4 pb-safe-bottom">
        <div className="mx-auto w-full max-w-lg py-4">
          {/* Status message */}
          {status === 'scanning' && (
            <p className="mb-3 text-center text-sm font-semibold text-emerald-400">{message}</p>
          )}
          {(status === 'error' || status === 'unsupported') && (
            <p className="mb-3 text-center text-xs text-rose-400">{message}</p>
          )}

          {/* Manual paste fallback */}
          <div>
            <label className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-zinc-400">
              Camera unavailable? Paste the QR link
            </label>
            <div className="flex gap-2">
              <input
                value={manualValue}
                onChange={(e) => setManualValue(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') handleManualOpen(); }}
                placeholder="https://…/verify?asset=…"
                className="min-w-0 flex-1 rounded-xl border border-zinc-700 bg-zinc-800 px-3 py-3 text-sm text-zinc-100 outline-none placeholder:text-zinc-500 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
              />
              <button
                onClick={handleManualOpen}
                className="rounded-xl bg-blue-600 px-4 text-sm font-bold text-white transition hover:bg-blue-500 active:scale-95"
              >
                Open
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
